### ISSUE TITLE
Disable -Werror for C++ builds

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice-demos#401]
Our C++ demos are failing to build with Xcode 16.3 due to:

```
In file included from IceDiscovery/replication/generated/Hello.h:27:
/opt/homebrew/include/Ice/Proxy.h:183:32: error: declaration shadows a local variable [-Werror,-Wshadow-uncaptured-local]
  183 |             _response = [this, response = std::move(response)](bool ok)
      |                                ^
/opt/homebrew/include/Ice/Proxy.h:174:51: note: previous declaration is here
  174 |                          ::std::function<void(R)> response,
      |                                                   ^
/opt/homebrew/include/Ice/Proxy.h:244:25: error: declaration shadows a local variable [-Werror,-Wshadow-uncaptured-local]
  244 |         _response = [&, response = std::move(response)](bool)
      |                         ^
/opt/homebrew/include/Ice/Proxy.h:238:88: note: previous declaration is here
  238 |                              ::std::function<void(::std::shared_ptr<Ice::Connection>)> response,
      |                                                                                        ^
/opt/homebrew/include/Ice/Proxy.h:600:18: error: declaration shadows a local variable [-Werror,-Wshadow-uncaptured-local]
  600 |             r = [response = std::move(response)](::Ice::Object::Ice_invokeResult&& result)
      |                  ^
/opt/homebrew/include/Ice/Proxy.h:590:77: note: previous declaration is here
  590 |                     ::std::function<void(bool, ::std::vector<::Ice::Byte>)> response,
      |                                                                             ^
/opt/homebrew/include/Ice/Proxy.h:690:18: error: declaration shadows a local variable [-Werror,-Wshadow-uncaptured-local]
  690 |             r = [response = std::move(response)](Result&& result)
      |                  ^
/opt/homebrew/include/Ice/Proxy.h:678:102: note: previous declaration is here
  678 |                     ::std::function<void(bool, ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>)> response,
```

We can fix the makefiles to ignore this warning but I think we should also remove -Werror for the demos. It's not helpful for users whatsoever.
